### ISSUE TITLE
After VSCode restart emmet support doesn't work anymore

### ISSUE THREAD

**Issue by exv3** [gencer/SCSS-Everywhere#12]
**OS** version `Windows 7`
**VSCode** version `1.31.0`
**Extension** version `1.2.1`

After I restart VSCode emmet support doesn't work anymore and I have to re-enable extension's setting to make it work again. 

![](https://i.imgur.com/OBSg1ko.gif)
![](https://i.imgur.com/8nlXTNT.gif)

**Comment by gencer** [comment]
Thanks for catching this too. I will also look into this.

**Comment by viccher** [comment]
Hello!
Thanks for this extension, it is very useful!

I have the same problem.
OS version: Windows 10,
VS Code version: 1.41.1 (system setup);
Extension version: 1.5.23.

**Comment by gencer** [comment]
I will look into this next weekend. To be honest, I never worked on `emmet` support. As it came from original project. This is fork of it. I will see whats behind the problem and compare with `master` there

**Comment by viccher** [comment]
Thanks for the quick response!
I use Emmet like this:
- after typing '.' I select the desired class from the suggested list,
- then I delete the last letter (or character),
- then I type this letter (or character) manually.
The result is an Emmet suggestion for creating a <div> with the selected class. For me it’s faster than without Emmet.

**Comment by dsod** [comment]
Hi,
Saw that they have fixed this in the original project.
See more information here:
https://github.com/zignd/HTML-CSS-Class-Completion/pull/129
https://github.com/zignd/HTML-CSS-Class-Completion/pull/129/commits/be670b60f94bcaa0e62af7aeda6fded15e0e07f0

**Comment by gencer** [comment]
@dsod Thanks for bringing this to my attention. I will create a fix soon based on that PR.

**Comment by gencer** [comment]
I've published a new version. Please check and reopen if needed.
