### ISSUE TITLE
Add some basic support for HAML

### ISSUE THREAD

**Issue by ndbroadbent** [gencer/SCSS-Everywhere#52]
Hello! Would it be possible to add some basic support for HAML? I think this should be very similar to Slim, and it would be super helpful. Thanks!

**Comment by gencer** [comment]
Hey @ndbroadbent!

In haml, do we use also hashtag `#` for ID's and dots `.` for classes?

**Comment by ndbroadbent** [comment]
Hi @gencer, yes that's the same!

**Comment by gencer** [comment]
Yws, we do! Checked on haml website.

Changes are on `master`

**Comment by gencer** [comment]
# v1.7.5

Can you test this version and let me know?

[html-slim-scss-css-class-completion-1.7.5.zip](https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion/files/4570255/html-slim-scss-css-class-completion-1.7.5.zip)

**Comment by ndbroadbent** [comment]
Hi @gencer, I tested v1.7.5 and it works great! Thanks very much for working on that so fast!
