### ISSUE TITLE
Update link to Svelte extension

### ISSUE THREAD

**Issue by dummdidumm** [gencer/SCSS-Everywhere#55]
In your main README, you refer to the old `Svelte` extension (https://marketplace.visualstudio.com/items?itemName=JamesBirtles.svelte-vscode). Please update the link to the new, official extension: https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode .

**Comment by gencer** [comment]
Thanks @dummdidumm to notify me for this update. I just changed it on README.

**Comment by dummdidumm** [comment]
Thanks 🥳
