### ISSUE TITLE
liquid support needed

### ISSUE THREAD

**Issue by FDiskas** [gencer/SCSS-Everywhere#59]

**Comment by gencer** [comment]
Liquid? Can you be more specific? I never heard of liquid.

**Comment by FDiskas** [comment]
There is a repo https://github.com/Shopify/liquid

**Comment by gencer** [comment]
It has a HTML-based syntax like Twig. Will be easy to add this support.

**Comment by gencer** [comment]
What do you use for Liquid Template Syntax on VSCode? Can you give me a VSCode Marketplace link?

**Comment by FDiskas** [comment]
I'm using 
```
    "killalau.vscode-liquid-snippets",
    "youhan.vscode-snippets-shopify-content-schema",
```

**Comment by FDiskas** [comment]
So far so good. Just missing "gotodefinition" functionality

**Comment by FDiskas** [comment]
And actualy "neilding.language-liquid" extention works better with yours instead "sissel.shopify-liquid" as you pointed in readme

**Comment by gencer** [comment]
If my extension works with `neilding.language-liquid` better than I will change the README.

**Comment by gencer** [comment]
> So far so good. Just missing "gotodefinition" functionality.

Go To Definition is **not** available on any languages in this extension. I am thinking to add this functionality but not yet decided how should I go.

**Comment by gencer** [comment]
**Released** on Open VSX and VSCode Marketplace as `v1.7.7`
