### ISSUE TITLE
Not getting suggestions

### ISSUE THREAD

**Issue by oxk4r01** [gencer/SCSS-Everywhere#62]
I'm not getting suggestions in any direction (nor html, nor css, nor handlebars...). Maybe i'm missing something... 
regards.
![image](https://user-images.githubusercontent.com/1032224/102243137-1ed63400-3efb-11eb-817c-74a9469f75ea.png)

**Comment by gencer** [comment]
Interesting. I just created a folder and 2 files. It seems i can make it work with latest version:

![image](https://user-images.githubusercontent.com/1711576/102288529-bb292680-3f4d-11eb-9a62-342a9c7f8b6e.png)
![image](https://user-images.githubusercontent.com/1711576/102288542-c1b79e00-3f4d-11eb-9a6c-3aef2537611e.png)

These extensions installed on my `vscode`:

![image](https://user-images.githubusercontent.com/1711576/102288612-e875d480-3f4d-11eb-8f8b-adb2797a67d0.png)

**Comment by gencer** [comment]
P.S.: Did you tweaked any settings for this plugin?

**Comment by gencer** [comment]
Ah, I noticed that, you wrote:

```
class
```

**not**

```
.class
```

Classes in CSS starts with `.` dot.

**Comment by oxk4r01** [comment]
Prepending point or not I get same behavior. Same for ids:
![image](https://user-images.githubusercontent.com/1032224/102342867-27317c00-3f9a-11eb-8d83-496cfec5cfc1.png)
![image](https://user-images.githubusercontent.com/1032224/102342893-3284a780-3f9a-11eb-859c-bc8d6a3318d8.png)
Settings are untouched...
![image](https://user-images.githubusercontent.com/1032224/102343139-75df1600-3f9a-11eb-99ed-687d203ed885.png)

**Comment by gencer** [comment]
Can you also show me when you search for `html-css-class-completion` in settings instead of `@ext: gencer...`?

Do you use Remote SSH/WSL?

**Comment by oxk4r01** [comment]
I tried without workspace but same behavior.

-> Do you use Remote SSH/WSL?
    No.

-> Can you also show me when you search for html-css-class-completion in settings instead of @ext: gencer...?
    Yes, but I get 49 settings. Doesn't fit in a single screenshot... 

![image](https://user-images.githubusercontent.com/1032224/102346039-901af300-3f9e-11eb-94e6-0ccb79e21fc9.png)
![image](https://user-images.githubusercontent.com/1032224/102346101-a2952c80-3f9e-11eb-8cd9-6512de958fbc.png)
![image](https://user-images.githubusercontent.com/1032224/102346164-b5a7fc80-3f9e-11eb-84aa-b0f0b7c40848.png)
![image](https://user-images.githubusercontent.com/1032224/102346193-c0fb2800-3f9e-11eb-8ff3-f3c86f8749de.png)
![image](https://user-images.githubusercontent.com/1032224/102346224-cc4e5380-3f9e-11eb-98af-f5a3b228063e.png)

**Comment by gencer** [comment]
Hm.. Looks like my extension is either:

a. Not enabled. So, Disabled.
b. Not installed (maybe?)
c. Something interfere my extension so that it doesn't get load into your VSCode.

Because, This is what you should see when you search that setting:

![image](https://user-images.githubusercontent.com/1711576/102346964-c3ff1400-3fb0-11eb-868e-8a662252ad59.png)

**Comment by oxk4r01** [comment]
> Hm.. Looks like my extension is either:
> 
> a. Not enabled. So, Disabled.
> b. Not installed (maybe?)
> c. Something interfere my extension so that it doesn't get load into your VSCode.
> 
> Because, This is what you should see when you search that setting:
> 
> ![image](https://user-images.githubusercontent.com/1711576/102346964-c3ff1400-3fb0-11eb-868e-8a662252ad59.png)

Extension was disabled. I don't know why, but sorry because I overlooked the most simple cause :( Thanks a lot for the support and regards!!!

**Comment by gencer** [comment]
No worries @oxk4r01. Glad you dif found the issue 🎉. Happy to help.

**Comment by COD3BREAK3R** [comment]
Actually dont work for me when i add a new class
